/**
 * Chapter 0：C 数据结构预备知识。
 * 不默认学生已掌握：struct / typedef / 指针 / 指针与数组 / malloc/free / 递归 / 函数参数 / 地址 / NULL / sizeof。
 */
import type { Chapter, CProgramRef } from '../types';

export const CH00_C_PROGRAMS: CProgramRef[] = [
  {
    id: 'ch00-struct',
    title: '结构体：把相关数据打包',
    lines: [
      '/* 结构体：把一个"学生"的多个属性打包成一种新类型 */',
      '#include <stdio.h>',
      '',
      'struct Student {',
      '    int id;            /* 学号 */',
      '    char name[20];     /* 姓名（字符数组） */',
      '    double score;      /* 分数 */',
      '};',
      '',
      'int main(void) {',
      '    struct Student s1 = {1001, "Alice", 92.5};  /* 定义并初始化 */',
      '    printf("id=%d score=%.1f\\n", s1.id, s1.score);  /* 点号访问成员 */',
      '    return 0;',
      '}',
    ],
    notes: {
      4: 'struct 定义的是"类型的图纸"，本身不占用内存，直到用它定义变量。',
      11: 's1 是图纸造出来的"房子"，编译器按成员顺序分配内存。',
      13: '结构体变量用 点号 访问成员；指针变量用 -> 访问（下一节）。',
    },
  },
  {
    id: 'ch00-typedef',
    title: 'typedef：给类型起别名',
    lines: [
      '/* typedef：以后写 Node 就等于写 struct Node */',
      'typedef struct Node {',
      '    int data;',
      '    struct Node *next;   /* 注意：这里还得写全名，因为别名还没生效 */',
      '} Node;',
      '',
      'int main(void) {',
      '    Node n = {10, NULL};     /* 不用再写 struct Node */',
      '    Node *p = &n;            /* 指向 n 的指针 */',
      '    printf("%d\\n", p->data); /* 指针用 -> 访问成员 */',
      '    return 0;',
      '}',
    ],
    notes: {
      2: 'typedef 让 struct Node 拥有短名 Node，数据结构代码几乎都这样写。',
      4: '自引用时（next 指向同类型）必须写完整 struct Node。',
      9: 'p->data 等价于 (*p).data，读作"p 指向的节点的 data"。',
    },
  },
  {
    id: 'ch00-pointer',
    title: '指针：存地址的变量',
    lines: [
      '/* 指针入门：变量、地址、解引用 */',
      '#include <stdio.h>',
      '',
      'int main(void) {',
      '    int a = 10;        /* a 是一个 int 变量 */',
      '    int *p = &a;       /* &a 取 a 的地址，p 存这个地址 */',
      '',
      '    printf("a = %d\\n", a);        /* 10：直接访问 */',
      '    printf("&a = %p\\n", (void *)&a); /* a 的地址 */',
      '    printf("p = %p\\n", (void *)p);   /* p 里存的值就是 a 的地址 */',
      '    printf("*p = %d\\n", *p);      /* 10：顺着地址找到 a（解引用） */',
      '',
      '    *p = 99;           /* 通过指针改写 a */',
      '    printf("a = %d\\n", a);        /* 99：a 被改了！ */',
      '    return 0;',
      '}',
    ],
    notes: {
      5: 'a 的值是 10；&a 是 a 在内存中的地址（如 0x2000）。',
      6: 'p 是"指向 int 的指针"，它自己的值是 a 的地址。p 也有自己的地址。',
      10: '*p 读作"p 指向的东西"。* 是解引用操作符，与定义时的 * 含义不同。',
      13: '对 *p 赋值 = 改写 p 所指的内存。这是链表修改节点的原理。',
    },
  },
  {
    id: 'ch00-ptr-array',
    title: '指针与数组',
    lines: [
      '/* 数组名在表达式里会"退化"为指向首元素的指针 */',
      '#include <stdio.h>',
      '',
      'int main(void) {',
      '    int a[5] = {10, 20, 30, 40, 50};',
      '    int *p = a;              /* 等价于 &a[0] */',
      '',
      '    printf("%d %d\\n", a[2], p[2]);   /* 一样：30 */',
      '    printf("%d\\n", *(p + 2));        /* 也是 30：地址算术 */',
      '',
      '    p = p + 1;               /* p 前进到 a[1] */',
      '    printf("%d\\n", *p);             /* 20 */',
      '    return 0;',
      '}',
    ],
    notes: {
      6: 'a[i] 本质是 *(a + i)：首地址偏移 i 个元素。这就是"下标访问"的真相。',
      9: 'p + 1 不是地址加 1 字节，而是加 sizeof(int) 字节——指针算术按元素大小移动。',
      11: 'p 可以改，a 不能（a 是地址常量）。所以遍历常用指针变量。',
    },
  },
  {
    id: 'ch00-malloc',
    title: 'malloc / free：堆内存',
    lines: [
      '/* 动态内存：运行时才决定要多大 */',
      '#include <stdio.h>',
      '#include <stdlib.h>',
      '',
      'int main(void) {',
      '    int n;',
      '    scanf("%d", &n);',
      '',
      '    int *arr = (int *)malloc(n * sizeof(int));  /* 申请 n 个 int */',
      '    if (arr == NULL) {',
      '        printf("内存不足\\n");',
      '        return 1;',
      '    }',
      '    for (int i = 0; i < n; i++) {',
      '        arr[i] = i * i;',
      '    }',
      '    printf("%d\\n", arr[n - 1]);',
      '',
      '    free(arr);       /* 用完必须归还，否则内存泄漏 */',
      '    arr = NULL;      /* 好习惯：防止悬垂指针被误用 */',
      '    return 0;',
      '}',
    ],
    notes: {
      9: 'malloc 参数是字节数，所以必须 n * sizeof(int)。返回 void*，C 中可直接赋给 int*。',
      10: 'malloc 可能失败（返回 NULL），不检查就用 = 崩溃。',
      19: 'free 归还内存，但 arr 里的地址还在（悬垂），所以紧接着置 NULL。',
    },
  },
  {
    id: 'ch00-recursion',
    title: '递归：函数调用自己',
    lines: [
      '/* 递归阶乘：n! = n × (n-1)! */',
      '#include <stdio.h>',
      '',
      'int fact(int n) {',
      '    if (n <= 1) {',
      '        return 1;            /* 递归出口：没有它就无限调用 */',
      '    }',
      '    return n * fact(n - 1);  /* 大问题拆成小问题 */',
      '}',
      '',
      'int main(void) {',
      '    printf("%d\\n", fact(4));   /* 24 */',
      '    return 0;',
      '}',
    ],
    notes: {
      5: '递归出口（base case）：最小的、能直接回答的情况。',
      8: '递归调用会压入调用栈。fact(4) 展开：4×fact(3)×…×fact(1)，然后逐层返回。',
    },
  },
  {
    id: 'ch00-func-params',
    title: '函数参数：值传递',
    lines: [
      '/* C 的函数参数是"复制一份"（值传递） */',
      '#include <stdio.h>',
      '',
      'void tryChange(int x) {',
      '    x = 100;              /* 只改了副本 */',
      '}',
      '',
      'void reallyChange(int *x) {',
      '    *x = 100;             /* 顺着地址改外面的变量 */',
      '}',
      '',
      'int main(void) {',
      '    int a = 1;',
      '    tryChange(a);',
      '    printf("%d\\n", a);    /* 1：没变 */',
      '    reallyChange(&a);',
      '    printf("%d\\n", a);    /* 100：变了 */',
      '    return 0;',
      '}',
    ],
    notes: {
      4: '传值：x 是 a 的拷贝，改 x 不影响 a。想在函数里改外部变量，只能传地址。',
      9: '传指针本质也是值传递——只不过复制的是"地址"这个值。',
      16: '这也是为什么数据结构函数总是传 SeqList* / Node*：要在函数里改结构本身。',
    },
  },
  {
    id: 'ch00-sizeof-null',
    title: 'sizeof 与 NULL',
    lines: [
      '/* sizeof：编译期算出类型/变量占多少字节；NULL：空指针 */',
      '#include <stdio.h>',
      '#include <stdlib.h>',
      '',
      'typedef struct Node {',
      '    int data;',
      '    struct Node *next;',
      '} Node;',
      '',
      'int main(void) {',
      '    printf("int: %zu\\n", sizeof(int));        /* 4 */',
      '    printf("Node: %zu\\n", sizeof(Node));      /* 16（4+4+对齐填充 或 4+8）*/',
      '    printf("Node*: %zu\\n", sizeof(Node *));   /* 8：指针大小与类型无关 */',
      '',
      '    Node *p = NULL;',
      '    if (p == NULL) {         /* 判空是好习惯 */',
      '        printf("p 不指向任何节点\\n");',
      '    }',
      '    /* *p = 1;  ← 千万别解引用 NULL，程序直接崩溃 */',
      '    return 0;',
      '}',
    ],
    notes: {
      12: 'sizeof(Node) 由编译器算（含对齐填充），手算容易错——所以 malloc(sizeof(Node)) 是标准写法。',
      14: '64 位系统上所有指针都是 8 字节，与指向什么无关。',
      18: 'NULL 表示"哪都不指"。访问前判空能避免大量崩溃。链表结尾的 next 就是 NULL。',
    },
  },
];

export const CH00: Chapter = {
  id: 0,
  title: 'C 数据结构预备知识',
  subtitle: '把学数据结构需要的 C 语言底子一次打牢',
  keywords: ['struct', 'typedef', '指针', '地址', 'malloc', 'free', '递归', 'NULL', 'sizeof', '函数参数', '预备知识'],
  sections: [
    {
      kind: 'what',
      title: '这一章是什么',
      body: [
        '这一章不讲数据结构本身，而是把学数据结构**必须**的 C 语言工具集中过一遍：结构体、typedef、指针、指针与数组、malloc/free、递归、函数参数、地址、NULL、sizeof。',
        '后面的每一章都建立在这些概念上。如果哪个小节读起来吃力，请先回到这里补课——尤其是指针小节，它是链表、树、图的地基。',
      ],
    },
    {
      kind: 'why',
      title: '为什么需要这些预备知识',
      bullets: [
        '数据结构 = 组织数据的方式 + 在其上的操作。C 里"组织数据"离不开 struct（打包）和指针（连接）。',
        '链表节点、树节点都在堆上动态创建：必须会用 malloc/free。',
        '递归是树和很多算法的天然描述：必须能看懂调用栈。',
        '函数要能修改外部结构：必须理解传地址。',
      ],
    },
    {
      kind: 'analogy',
      title: '类比：内存是一排储物柜',
      bullets: [
        '内存 = 一排带编号（地址）的储物柜。',
        '变量 = 贴了名字标签的柜子；值 = 柜子里放的东西。',
        '指针 = 一张写着"某柜子编号"的纸条。纸条本身也放在某个柜子里。',
        'NULL = 纸条上写着"无"，顺着它找不到任何柜子。',
        'malloc = 向管理员申请一段连续空柜子；free = 归还。忘了归还会越占越多（内存泄漏）。',
      ],
    },
    {
      kind: 'diagram',
      title: '指针图示',
      body: [
        '```',
        'int a = 10;      int *p = &a;',
        '',
        '      p                a',
        '  ┌───────┐        ┌────┐',
        '  │0x2000 │──┐     │ 10 │   地址 0x2000',
        '  └───────┘  └───→ └────┘',
        '   p 的值是           a 的地址',
        '   a 的地址           a 的值是 10',
        '```',
        '解引用 *p 就是"顺着 p 里的地址走过去，看/改那个柜子"。',
      ],
      vizOps: [{ op: 'memory-pointer', label: '打开内存面板：看 a 与 p 的地址关系' }],
    },
    {
      kind: 'struct',
      title: '结构体与 typedef（先睹为快）',
      body: [
        '数据结构的第一步永远是"定义节点长什么样"。两种写法都要认识：',
        '```c',
        '/* 写法一：先 struct 后变量 */',
        'struct Node { int data; struct Node *next; };',
        'struct Node n;',
        '',
        '/* 写法二：typedef 起别名（本书统一用这种） */',
        'typedef struct Node {',
        '    int data;',
        '    struct Node *next;',
        '} Node;',
        'Node n;   /* 简洁 */',
        '```',
      ],
      codeId: 'ch00-typedef',
    },
    {
      kind: 'operations',
      title: '本章覆盖的 10 个工具点',
      bullets: [
        'struct：把多个变量打包成一个新类型',
        'typedef：给类型起短名',
        '指针：存地址的变量；& 取地址、* 解引用',
        '指针与数组：a[i] 即 *(a+i)',
        'malloc/free：运行时申请/归还堆内存',
        '递归：出口 + 缩小问题 + 自己调用自己',
        '函数参数：值传递，改外部必须传地址',
        '地址：内存单元的编号',
        'NULL：空指针，判空防崩溃',
        'sizeof：类型的字节数，malloc 的标配',
      ],
    },
    {
      kind: 'code',
      title: '核心代码速查（右侧代码面板可逐行看解释）',
      body: ['下面 8 段代码覆盖全部知识点。每一段都可以在右侧代码面板里逐行查看解释：'],
      codeId: 'ch00-pointer',
    },
    {
      kind: 'animation',
      title: '动画：指针与内存',
      vizOps: [
        { op: 'memory-pointer', label: 'int a = 10; int *p = &a; 的内存图' },
        { op: 'memory-pointer-deref', label: '*p = 99 之后发生了什么' },
      ],
    },
    {
      kind: 'step',
      title: '单步建议',
      bullets: [
        '在"动画"小节打开内存面板，单步观察 p 的值如何等于 a 的地址。',
        '第 3 章学习链表时，回来看 malloc/free 的动画。',
      ],
    },
    {
      kind: 'time',
      title: '本章节出复杂度',
      body: ['本章不涉及算法复杂度。第 1 章将专门讲解大 O 记号。'],
    },
    {
      kind: 'space',
      title: '栈与堆',
      bullets: [
        '局部变量、函数参数：栈区，函数返回自动回收（快、容量小）。',
        'malloc 的内存：堆区，必须手动 free（慢、按需、容量大）。',
        '数据结构的节点全部生活在堆上——这是与"普通变量"最大的区别。',
      ],
    },
    {
      kind: 'pitfalls',
      title: '新手常犯错误',
      bullets: [
        '野指针：int *p; 之后直接 *p = 1（p 里是随机值）。先置 NULL 或赋有效地址。',
        '解引用 NULL：程序立刻崩溃（段错误）。',
        '内存泄漏：malloc 了不 free。',
        '重复 free / use-after-free：free 后继续用该指针。',
        'sizeof 误用：malloc(n) 而不是 malloc(n * sizeof(int))。',
        '以为函数能改外部变量：值传递改的只是副本。',
        '递归忘记出口：栈溢出崩溃。',
      ],
    },
    {
      kind: 'quiz',
      title: '小测验',
      body: ['学完这一章，去做几道题检验一下（题库 → 第 0 章）：'],
    },
    {
      kind: 'exercise',
      title: '编程练习',
      body: ['本章的编程练习侧重指针与内存基本功，在"代码练习"页选择第 0 章题目。'],
    },
  ],
};
