/**
 * 题库：第 11~13 章（图 / 查找 / 排序）。每章 ≥6 题。
 */
import type { Exercise } from '../types';

export const ALGO_BANK: Exercise[] = [
  /* ============ 第 11 章 图 ============ */
  {
    id: 'ch11-q01',
    chapter: 11,
    knowledgePoint: '图存储',
    difficulty: 2,
    type: 'single',
    question: 'n 个顶点的无向图用邻接矩阵存储，空间复杂度是？',
    options: [
      { id: 'A', text: 'O(n)' },
      { id: 'B', text: 'O(n + e)' },
      { id: 'C', text: 'O(n²)' },
      { id: 'D', text: 'O(e)' },
    ],
    answer: { type: 'single', value: 'C' },
    explanation: '矩阵固定 n×n，与边数无关；邻接表是 O(n+e)，稀疏图更省。',
    tags: ['图', '邻接矩阵'],
    errorCategory: 'complexity',
  },
  {
    id: 'ch11-q02',
    chapter: 11,
    knowledgePoint: 'DFS/BFS',
    difficulty: 2,
    type: 'single',
    question: 'DFS 和 BFS 分别借助什么辅助结构？',
    options: [
      { id: 'A', text: '队列；栈' },
      { id: 'B', text: '栈；队列' },
      { id: 'C', text: '都是栈' },
      { id: 'D', text: '都是队列' },
    ],
    answer: { type: 'single', value: 'B' },
    explanation: 'DFS 一条路走到黑（栈/递归）；BFS 一层层扩（队列）。',
    tags: ['DFS', 'BFS'],
    errorCategory: 'concept',
  },
  {
    id: 'ch11-q03',
    chapter: 11,
    knowledgePoint: 'visited',
    difficulty: 2,
    type: 'bug-find',
    question: '在有环图上做 DFS 忘记维护 visited 会怎样？',
    options: [
      { id: 'A', text: '沿环无限递归，栈溢出' },
      { id: 'B', text: '只是多算一次' },
      { id: 'C', text: '没有影响' },
    ],
    answer: { type: 'single', value: 'A' },
    explanation: 'visited 是图遍历与树遍历最大的区别：图可能有环，必须防止重复访问。',
    tags: ['图', 'visited'],
    errorCategory: 'algorithm',
  },
  {
    id: 'ch11-q04',
    chapter: 11,
    knowledgePoint: 'BFS 标记时机',
    difficulty: 3,
    type: 'single',
    question: 'BFS 中 visited 的正确标记时机是？',
    options: [
      { id: 'A', text: '出队时' },
      { id: 'B', text: '入队时' },
      { id: 'C', text: '都一样' },
    ],
    answer: { type: 'single', value: 'B' },
    explanation: '出队才标记会让同一顶点被多个邻居重复入队，队列爆炸。',
    tags: ['BFS', '队列'],
    errorCategory: 'algorithm',
  },
  {
    id: 'ch11-q05',
    chapter: 11,
    knowledgePoint: '无向图对称',
    difficulty: 2,
    type: 'judge',
    question: '无向图的邻接矩阵是对称矩阵，加边时要同时置 matrix[u][v] 和 matrix[v][u]。',
    options: [
      { id: 'A', text: '正确' },
      { id: 'B', text: '错误' },
    ],
    answer: { type: 'judge', value: true },
    explanation: '漏掉一半会导致遍历结果错误（边单向）。',
    tags: ['图', '邻接矩阵'],
    errorCategory: 'boundary',
  },
  {
    id: 'ch11-q06',
    chapter: 11,
    knowledgePoint: '遍历复杂度',
    difficulty: 2,
    type: 'multiple',
    question: '图遍历复杂度（邻接表存储），正确的有？',
    options: [
      { id: 'A', text: 'DFS 为 O(n + e)' },
      { id: 'B', text: 'BFS 为 O(n + e)' },
      { id: 'C', text: '邻接矩阵下都是 O(n²)' },
      { id: 'D', text: 'BFS 是 O(e²)' },
    ],
    answer: { type: 'multiple', value: ['A', 'B', 'C'] },
    explanation: '每个顶点和每条边各处理常数次（表存储）；矩阵要扫每行的 n 列。',
    tags: ['图', '复杂度'],
    errorCategory: 'complexity',
  },

  /* ============ 第 12 章 查找 ============ */
  {
    id: 'ch12-q01',
    chapter: 12,
    knowledgePoint: '二分前提',
    difficulty: 1,
    type: 'single',
    question: '二分查找的前提条件是？',
    options: [
      { id: 'A', text: '数据量足够大' },
      { id: 'B', text: '数据有序且支持随机访问' },
      { id: 'C', text: '数据无重复' },
    ],
    answer: { type: 'single', value: 'B' },
    explanation: '无序数组二分可能"路过"目标返回 -1；链表二分退化为 O(n)。',
    tags: ['二分查找'],
    errorCategory: 'concept',
  },
  {
    id: 'ch12-q02',
    chapter: 12,
    knowledgePoint: '二分过程',
    difficulty: 2,
    type: 'exec-result',
    question: '有序数组 [1,3,5,7,9,11,13,15] 二分查找 7：第一次比较的下标 mid 是？共比较几次找到？',
    answer: { type: 'text', value: ['mid=3，比较1次', '3,1', 'mid=3 比较1次'] },
    explanation: 'low=0 high=7，mid=(0+7)/2=3，a[3]=7 命中，1 次。',
    tags: ['二分查找'],
    errorCategory: 'algorithm',
  },
  {
    id: 'ch12-q03',
    chapter: 12,
    knowledgePoint: '二分死循环',
    difficulty: 3,
    type: 'bug-find',
    question: '```c\nwhile (low <= high) {\n    int mid = (low + high) / 2;\n    if (a[mid] < target) low = mid;      /* 有错 */\n    else high = mid - 1;\n}\n```\n错误在哪？',
    options: [
      { id: 'A', text: 'low = mid 应为 low = mid + 1，否则区间不缩小会死循环' },
      { id: 'B', text: 'while 条件应为 low < high' },
      { id: 'C', text: 'mid 计算方式错误' },
    ],
    answer: { type: 'single', value: 'A' },
    explanation: '当 low==mid 时赋值后区间不变，永远循环。+1/-1 是保证区间严格缩小的关键。',
    tags: ['二分', '死循环'],
    errorCategory: 'loop',
  },
  {
    id: 'ch12-q04',
    chapter: 12,
    knowledgePoint: 'mid 溢出',
    difficulty: 3,
    type: 'code-complete',
    question: '防溢出的 mid 计算写法：\n```c\nint mid = ____1____ + (____2____) / 2;\n```',
    answer: { type: 'blanks', value: [['low'], ['high - low']] },
    explanation: '(low+high) 在两端都很大时会溢出 int；low + (high-low)/2 数学等价且安全。',
    tags: ['二分', '溢出'],
    errorCategory: 'boundary',
  },
  {
    id: 'ch12-q05',
    chapter: 12,
    knowledgePoint: '查找复杂度',
    difficulty: 2,
    type: 'single',
    question: '在 1024 个有序元素中二分查找，最坏比较次数约？',
    options: [
      { id: 'A', text: '10 次' },
      { id: 'B', text: '512 次' },
      { id: 'C', text: '1024 次' },
    ],
    answer: { type: 'single', value: 'A' },
    explanation: 'log₂1024 = 10。每次排除一半。',
    tags: ['二分', '复杂度'],
    errorCategory: 'complexity',
  },
  {
    id: 'ch12-q06',
    chapter: 12,
    knowledgePoint: '顺序查找',
    difficulty: 1,
    type: 'judge',
    question: '顺序查找不要求数据有序，平均要比较约 n/2 次。',
    options: [
      { id: 'A', text: '正确' },
      { id: 'B', text: '错误' },
    ],
    answer: { type: 'judge', value: true },
    explanation: '找到平均 n/2，找不到 n。O(n)。',
    tags: ['顺序查找'],
    errorCategory: 'complexity',
  },

  /* ============ 第 13 章 排序 ============ */
  {
    id: 'ch13-q01',
    chapter: 13,
    knowledgePoint: '排序稳定性',
    difficulty: 2,
    type: 'multiple',
    question: '下列排序中稳定的有？',
    options: [
      { id: 'A', text: '冒泡排序' },
      { id: 'B', text: '插入排序' },
      { id: 'C', text: '归并排序' },
      { id: 'D', text: '快速排序' },
    ],
    answer: { type: 'multiple', value: ['A', 'B', 'C'] },
    explanation: '冒泡相等不交换、插入相等停止、归并取等号先左——都保序。快排的远距离交换破坏稳定性。',
    tags: ['排序', '稳定性'],
    errorCategory: 'concept',
  },
  {
    id: 'ch13-q02',
    chapter: 13,
    knowledgePoint: '快排',
    difficulty: 2,
    type: 'single',
    question: '快速排序最坏时间复杂度及触发条件？',
    options: [
      { id: 'A', text: 'O(n²)；数组已有序且固定取端点为 pivot' },
      { id: 'B', text: 'O(n²)；数据随机' },
      { id: 'C', text: 'O(n log n)；任何情况' },
    ],
    answer: { type: 'single', value: 'A' },
    explanation: '有序输入使每趟分区极度倾斜（0 与 n-1）。随机化 pivot 可规避。',
    tags: ['快排'],
    errorCategory: 'complexity',
  },
  {
    id: 'ch13-q03',
    chapter: 13,
    knowledgePoint: '冒泡优化',
    difficulty: 2,
    type: 'exec-result',
    question: '对已有序数组 [1,2,3,4,5] 用带 swapped 标志的冒泡排序，共比较几次后提前结束？',
    answer: { type: 'text', value: ['4'] },
    explanation: '第一趟比较 4 次无交换，提前结束——这是冒泡对有序输入 O(n) 的优化。',
    tags: ['冒泡'],
    errorCategory: 'algorithm',
  },
  {
    id: 'ch13-q04',
    chapter: 13,
    knowledgePoint: '插入排序',
    difficulty: 2,
    type: 'code-complete',
    question: '插入排序核心：\n```c\nint key = a[i];\nint j = i - 1;\nwhile (j >= 0 && ____1____) {\n    a[j + 1] = ____2____;\n    j--;\n}\na[j + 1] = key;\n```',
    answer: { type: 'blanks', value: [['a[j] > key'], ['a[j]']] },
    explanation: '比 key 大的逐个右移；循环退出位置+1 就是 key 的家。',
    tags: ['插入排序'],
    errorCategory: 'loop',
  },
  {
    id: 'ch13-q05',
    chapter: 13,
    knowledgePoint: '排序选择',
    difficulty: 3,
    type: 'single',
    question: '需要稳定且最坏也是 O(n log n) 的排序，选哪个？',
    options: [
      { id: 'A', text: '快速排序' },
      { id: 'B', text: '归并排序' },
      { id: 'C', text: '堆排序' },
      { id: 'D', text: '希尔排序' },
    ],
    answer: { type: 'single', value: 'B' },
    explanation: '堆/希尔不稳定；快排最坏 O(n²)。归并稳定且最坏 O(n log n)（代价 O(n) 空间）。',
    tags: ['排序', '选择'],
    errorCategory: 'complexity',
  },
  {
    id: 'ch13-q06',
    chapter: 13,
    knowledgePoint: '归并思想',
    difficulty: 2,
    type: 'single',
    question: '归并排序合并两个长度分别为 a、b 的有序数组，比较次数最多？',
    options: [
      { id: 'A', text: 'a + b' },
      { id: 'B', text: 'a + b - 1' },
      { id: 'C', text: 'min(a, b)' },
    ],
    answer: { type: 'single', value: 'B' },
    explanation: '每次比较取走一个元素，最后一个不用比。归并是线性 O(n) 的分治合并。',
    tags: ['归并'],
    errorCategory: 'algorithm',
  },
  {
    id: 'ch13-q07',
    chapter: 13,
    knowledgePoint: '排序复杂度',
    difficulty: 2,
    type: 'multiple',
    question: '平均 O(n log n) 的排序有？',
    options: [
      { id: 'A', text: '归并' },
      { id: 'B', text: '快排' },
      { id: 'C', text: '堆排序' },
      { id: 'D', text: '选择排序' },
    ],
    answer: { type: 'multiple', value: ['A', 'B', 'C'] },
    explanation: '选择排序无论输入如何都是 O(n²)。',
    tags: ['排序', '复杂度'],
    errorCategory: 'complexity',
  },
];
