/**
 * 题库：第 7~10 章（字符串数组 / 树 / BST / 堆）。每章 ≥6 题。
 */
import type { Exercise } from '../types';

export const TREE_BANK: Exercise[] = [
  /* ============ 第 7 章 字符串与数组 ============ */
  {
    id: 'ch07-q01',
    chapter: 7,
    knowledgePoint: '二维数组地址',
    difficulty: 2,
    type: 'single',
    question: 'int m[3][4]（行优先存储），m[1][2] 相对首地址偏移多少个 int？',
    options: [
      { id: 'A', text: '3' },
      { id: 'B', text: '5' },
      { id: 'C', text: '6' },
      { id: 'D', text: '7' },
    ],
    answer: { type: 'single', value: 'C' },
    explanation: '偏移 = 行号×列数 + 列号 = 1×4 + 2 = 6。二维数组本质是拉平的一维内存。',
    tags: ['二维数组', '地址'],
    errorCategory: 'concept',
  },
  {
    id: 'ch07-q02',
    chapter: 7,
    knowledgePoint: '字符串结尾',
    difficulty: 1,
    type: 'judge',
    question: 'C 字符串必须以 \\0 结尾，strcpy 会把它一起复制。',
    options: [
      { id: 'A', text: '正确' },
      { id: 'B', text: '错误' },
    ],
    answer: { type: 'judge', value: true },
    explanation: '自己实现复制时漏掉 \\0 是经典 bug：printf 会一直读出数组之外。',
    tags: ['字符串'],
    errorCategory: 'boundary',
  },
  {
    id: 'ch07-q03',
    chapter: 7,
    knowledgePoint: '数组越界',
    difficulty: 1,
    type: 'bug-find',
    question: 'int a[5]; a[5] = 1; 的问题是什么？',
    options: [
      { id: 'A', text: '越界写：合法下标是 0..4' },
      { id: 'B', text: 'a[5] 应为 a(5)' },
      { id: 'C', text: '没有问题' },
    ],
    answer: { type: 'single', value: 'A' },
    explanation: 'C 不检查越界，写 a[5] 破坏相邻内存，可能不崩溃但埋雷。',
    tags: ['数组', '越界'],
    errorCategory: 'boundary',
  },
  {
    id: 'ch07-q04',
    chapter: 7,
    knowledgePoint: 'strlen 性能',
    difficulty: 2,
    type: 'code-read',
    question: '```c\nfor (int i = 0; i < strlen(s); i++) { … }\n```\n这段代码的问题？',
    options: [
      { id: 'A', text: '每次循环都重新计算 strlen，O(n²)' },
      { id: 'B', text: 'i 的类型错误' },
      { id: 'C', text: '没有问题' },
    ],
    answer: { type: 'single', value: 'A' },
    explanation: 'strlen 是 O(n) 的。应先 size_t len = strlen(s); 再用 len。',
    tags: ['strlen', '性能'],
    errorCategory: 'complexity',
  },
  {
    id: 'ch07-q05',
    chapter: 7,
    knowledgePoint: '数组存储',
    difficulty: 1,
    type: 'multiple',
    question: '关于数组，正确的有？',
    options: [
      { id: 'A', text: '数组元素在内存中连续存放' },
      { id: 'B', text: 'a[i] 等价于 *(a + i)' },
      { id: 'C', text: '数组名可作为指向首元素的指针使用' },
      { id: 'D', text: '数组名可以被重新赋值指向别处' },
    ],
    answer: { type: 'multiple', value: ['A', 'B', 'C'] },
    explanation: '数组名是地址常量，不可赋值；指针变量才可以 p = p + 1。',
    tags: ['数组', '指针'],
    errorCategory: 'concept',
  },
  {
    id: 'ch07-q06',
    chapter: 7,
    knowledgePoint: '手写 strlen',
    difficulty: 2,
    type: 'code-complete',
    question: '补全 myStrlen：\n```c\nsize_t myStrlen(const char *s) {\n    size_t len = 0;\n    while (____1____ != \'\\0\') {\n        ____2____;\n    }\n    return len;\n}\n```',
    answer: { type: 'blanks', value: [['s[len]'], ['len++']] },
    explanation: '数到结尾符为止，不含 \\0。',
    tags: ['字符串', 'strlen'],
    errorCategory: 'loop',
  },

  /* ============ 第 8 章 树 ============ */
  {
    id: 'ch08-q01',
    chapter: 8,
    knowledgePoint: '遍历结果',
    difficulty: 2,
    type: 'exec-result',
    question: '树：8 的左孩子 3（3 的孩子 1、6），右孩子 10。中序遍历输出（空格分隔）？',
    answer: { type: 'text', value: ['1 3 6 8 10'] },
    explanation: '中序 = 左根右：1、3、6、8、10。',
    tags: ['树', '中序'],
    errorCategory: 'algorithm',
  },
  {
    id: 'ch08-q02',
    chapter: 8,
    knowledgePoint: '遍历性质',
    difficulty: 2,
    type: 'single',
    question: '先序遍历的第一个元素和后序遍历的最后一个元素分别是？',
    options: [
      { id: 'A', text: '根；根' },
      { id: 'B', text: '最左叶；根' },
      { id: 'C', text: '根；最右叶' },
    ],
    answer: { type: 'single', value: 'A' },
    explanation: '先序"根左右"第一个访问根；后序"左右根"最后访问根。',
    tags: ['树', '遍历'],
    errorCategory: 'algorithm',
  },
  {
    id: 'ch08-q03',
    chapter: 8,
    knowledgePoint: '销毁树',
    difficulty: 2,
    type: 'single',
    question: '销毁二叉树应该用哪种遍历？为什么？',
    options: [
      { id: 'A', text: '先序：先释放自己最方便' },
      { id: 'B', text: '后序：必须先释放孩子，否则找不到他们' },
      { id: 'C', text: '层序：队列最自然' },
    ],
    answer: { type: 'single', value: 'B' },
    explanation: '先 free 自己就丢了左右孩子指针。后序保证处理完子树才轮到自己。',
    tags: ['树', '后序', '销毁'],
    errorCategory: 'memory',
  },
  {
    id: 'ch08-q04',
    chapter: 8,
    knowledgePoint: '层序遍历',
    difficulty: 2,
    type: 'multiple',
    question: '层序遍历借助队列，正确的有？',
    options: [
      { id: 'A', text: '根节点先入队' },
      { id: 'B', text: '出队一个节点后访问它，并把它的孩子入队' },
      { id: 'C', text: '孩子入队时立即标记，防止重复入队' },
      { id: 'D', text: '应该用栈而不是队列' },
    ],
    answer: { type: 'multiple', value: ['A', 'B', 'C'] },
    explanation: '队列的 FIFO 保证按层展开；用栈就变成 DFS。',
    tags: ['层序', '队列'],
    errorCategory: 'algorithm',
  },
  {
    id: 'ch08-q05',
    chapter: 8,
    knowledgePoint: '递归出口',
    difficulty: 1,
    type: 'bug-find',
    question: '写树的递归遍历时，忘记写 if (node == NULL) return; 会怎样？',
    options: [
      { id: 'A', text: '递归无法终止/对 NULL 解引用，栈溢出或崩溃' },
      { id: 'B', text: '只是输出顺序不对' },
      { id: 'C', text: '没有影响' },
    ],
    answer: { type: 'single', value: 'A' },
    explanation: '递归出口是终止条件，漏掉就是无限递归。',
    tags: ['树', '递归'],
    errorCategory: 'boundary',
  },
  {
    id: 'ch08-q06',
    chapter: 8,
    knowledgePoint: '由遍历重建',
    difficulty: 3,
    type: 'single',
    question: '已知先序 ABC 和中序 BAC，树的结构是？',
    options: [
      { id: 'A', text: 'A 为根，B 为左孩子，C 为右孩子' },
      { id: 'B', text: 'A 为根，只有右孩子链 B→C' },
      { id: 'C', text: 'B 为根' },
    ],
    answer: { type: 'single', value: 'A' },
    explanation: '先序首元素 A 是根；中序中 A 左边是 B（左子树）、右边是 C（右子树）。',
    tags: ['树', '重建'],
    errorCategory: 'algorithm',
  },

  /* ============ 第 9 章 BST ============ */
  {
    id: 'ch09-q01',
    chapter: 9,
    knowledgePoint: 'BST 性质',
    difficulty: 1,
    type: 'judge',
    question: 'BST 的中序遍历结果是升序序列。',
    options: [
      { id: 'A', text: '正确' },
      { id: 'B', text: '错误' },
    ],
    answer: { type: 'judge', value: true },
    explanation: '左<根<右 的性质在展开后就是升序。这也是验证 BST 的标准方法。',
    tags: ['BST', '中序'],
    errorCategory: 'concept',
  },
  {
    id: 'ch09-q02',
    chapter: 9,
    knowledgePoint: 'BST 查找',
    difficulty: 2,
    type: 'single',
    question: '在 BST 中查找 5：8→3→6→?（5 < 6），下一步去哪？',
    options: [
      { id: 'A', text: '6 的左子树' },
      { id: 'B', text: '6 的右子树' },
      { id: 'C', text: '回到 8' },
    ],
    answer: { type: 'single', value: 'A' },
    explanation: '5 < 6，目标只可能在左子树。',
    tags: ['BST', '查找'],
    errorCategory: 'algorithm',
  },
  {
    id: 'ch09-q03',
    chapter: 9,
    knowledgePoint: 'BST 删除',
    difficulty: 3,
    type: 'single',
    question: '删除有两个孩子的 BST 节点，本平台采用的方法是？',
    options: [
      { id: 'A', text: '直接删除，右子树丢弃' },
      { id: 'B', text: '用左子树最大节点（中序前驱）的值顶替，再删前驱' },
      { id: 'C', text: '把两个子树合并成一个' },
    ],
    answer: { type: 'single', value: 'B' },
    explanation: '前驱顶替保持 BST 性质；前驱没有右孩子，删除它必然退化为情形一/二。',
    tags: ['BST', '删除'],
    errorCategory: 'algorithm',
  },
  {
    id: 'ch09-q04',
    chapter: 9,
    knowledgePoint: 'BST 插入',
    difficulty: 2,
    type: 'exec-result',
    question: '空 BST 依次插入 8 3 10 1，根的左子树包含哪些值（升序）？',
    answer: { type: 'text', value: ['1 3', '1,3'] },
    explanation: '3 < 8 往左；10 > 8 往右；1 < 8 < 3 到 3 的左边。左子树 = {3,1}。',
    tags: ['BST', '插入'],
    errorCategory: 'algorithm',
  },
  {
    id: 'ch09-q05',
    chapter: 9,
    knowledgePoint: 'BST 退化',
    difficulty: 2,
    type: 'single',
    question: '按 1,2,3,4,5 的顺序插入 BST，得到什么形状？查找复杂度？',
    options: [
      { id: 'A', text: '平衡树；O(log n)' },
      { id: 'B', text: '右斜链（相当于链表）；O(n)' },
      { id: 'C', text: '左斜链；O(1)' },
    ],
    answer: { type: 'single', value: 'B' },
    explanation: '有序插入导致退化。AVL/红黑树通过旋转保持平衡（进阶内容）。',
    tags: ['BST', '退化'],
    errorCategory: 'algorithm',
  },
  {
    id: 'ch09-q06',
    chapter: 9,
    knowledgePoint: 'BST 复杂度',
    difficulty: 2,
    type: 'multiple',
    question: '平衡 BST 的查找/插入/删除复杂度，正确的有？',
    options: [
      { id: 'A', text: '查找平均 O(log n)' },
      { id: 'B', text: '插入平均 O(log n)' },
      { id: 'C', text: '最坏（退化为链）都是 O(n)' },
      { id: 'D', text: '中序遍历 O(log n)' },
    ],
    answer: { type: 'multiple', value: ['A', 'B', 'C'] },
    explanation: '遍历必须访问每个节点，是 O(n)。',
    tags: ['BST', '复杂度'],
    errorCategory: 'complexity',
  },

  /* ============ 第 10 章 堆 ============ */
  {
    id: 'ch10-q01',
    chapter: 10,
    knowledgePoint: '堆的下标',
    difficulty: 2,
    type: 'single',
    question: '0-based 数组存储的堆中，下标 4 的父节点和孩子们是？',
    options: [
      { id: 'A', text: '父 1；孩子 8、9' },
      { id: 'B', text: '父 2；孩子 9、10' },
      { id: 'C', text: '父 1；孩子 9、10' },
    ],
    answer: { type: 'single', value: 'C' },
    explanation: 'parent=(4-1)/2=1（整除）；children=2×4+1=9、2×4+2=10。',
    tags: ['堆', '下标'],
    errorCategory: 'boundary',
  },
  {
    id: 'ch10-q02',
    chapter: 10,
    knowledgePoint: '堆性质',
    difficulty: 2,
    type: 'judge',
    question: '最大堆中，任意节点的值都不小于它的两个孩子。',
    options: [
      { id: 'A', text: '正确' },
      { id: 'B', text: '错误' },
    ],
    answer: { type: 'judge', value: true },
    explanation: '注意：只约束父子，兄弟之间、跨子树之间没有大小关系。',
    tags: ['堆'],
    errorCategory: 'concept',
  },
  {
    id: 'ch10-q03',
    chapter: 10,
    knowledgePoint: '堆操作',
    difficulty: 2,
    type: 'single',
    question: '堆插入新元素的过程是？',
    options: [
      { id: 'A', text: '放数组末尾，向上和父节点比较交换（上滤）' },
      { id: 'B', text: '放数组头部，向下交换（下滤）' },
      { id: 'C', text: '全数组重新排序' },
    ],
    answer: { type: 'single', value: 'A' },
    explanation: '上滤最多走树高 O(log n)。放在末尾保证完全二叉树形状不破坏。',
    tags: ['堆', '上滤'],
    errorCategory: 'algorithm',
  },
  {
    id: 'ch10-q04',
    chapter: 10,
    knowledgePoint: '建堆',
    difficulty: 3,
    type: 'single',
    question: 'Floyd 建堆从哪个下标开始、什么方向？',
    options: [
      { id: 'A', text: '从 0 正向到最后' },
      { id: 'B', text: '从 n/2-1（最后非叶）倒序到 0，每个执行下滤' },
      { id: 'C', text: '从最后叶节点倒序' },
    ],
    answer: { type: 'single', value: 'B' },
    explanation: '叶子天然是堆；倒序保证下滤时子树已是堆。总代价 O(n)。',
    tags: ['堆', 'heapify'],
    errorCategory: 'algorithm',
  },
  {
    id: 'ch10-q05',
    chapter: 10,
    knowledgePoint: '堆排序',
    difficulty: 2,
    type: 'multiple',
    question: '关于堆排序，正确的有？',
    options: [
      { id: 'A', text: '升序排序用最大堆' },
      { id: 'B', text: '每趟把堆顶（最大）与末尾交换，堆缩小 1' },
      { id: 'C', text: '时间复杂度 O(n log n)' },
      { id: 'D', text: '需要 O(n) 辅助数组' },
    ],
    answer: { type: 'multiple', value: ['A', 'B', 'C'] },
    explanation: '堆排序原地进行，额外空间 O(1)。',
    tags: ['堆排序'],
    errorCategory: 'complexity',
  },
  {
    id: 'ch10-q06',
    chapter: 10,
    knowledgePoint: '堆判断',
    difficulty: 2,
    type: 'judge',
    question: '数组 [9, 7, 8, 3, 5] 是一个合法的最大堆。',
    options: [
      { id: 'A', text: '正确' },
      { id: 'B', text: '错误' },
    ],
    answer: { type: 'judge', value: true },
    explanation: '检查：9≥7,8；7≥3,5；8 无孩子（下标 2 的孩子 5、6 越界）。全部满足。',
    tags: ['堆', '判断'],
    errorCategory: 'concept',
  },
];
