/**
 * 题库：第 0~6 章（基础与线性结构）。每章 ≥6 题。
 */
import type { Exercise } from '../types';

export const LINEAR_BANK: Exercise[] = [
  /* ============ 第 0 章 预备知识 ============ */
  {
    id: 'ch00-q01',
    chapter: 0,
    knowledgePoint: '指针基础',
    difficulty: 1,
    type: 'single',
    question: 'int a = 10; int *p = &a; 执行后，p 里存的是什么？',
    options: [
      { id: 'A', text: '10' },
      { id: 'B', text: 'a 的地址' },
      { id: 'C', text: 'p 自己的地址' },
      { id: 'D', text: '不确定的随机值' },
    ],
    answer: { type: 'single', value: 'B' },
    explanation: 'p 是指针变量，&a 取 a 的地址赋给 p，所以 p 的值是 a 的地址。*p 才是 10。',
    tags: ['指针', '地址'],
    errorCategory: 'pointer',
  },
  {
    id: 'ch00-q02',
    chapter: 0,
    knowledgePoint: '解引用',
    difficulty: 1,
    type: 'judge',
    question: 'int a = 10; int *p = &a; 执行 *p = 99; 之后 a 的值变成 99。',
    options: [
      { id: 'A', text: '正确' },
      { id: 'B', text: '错误' },
    ],
    answer: { type: 'judge', value: true },
    explanation: '*p 表示"p 指向的内存"，对它赋值就是改写 a。这也是链表 current->next = x 的原理。',
    tags: ['指针', '解引用'],
    errorCategory: 'pointer',
  },
  {
    id: 'ch00-q03',
    chapter: 0,
    knowledgePoint: 'malloc/free',
    difficulty: 2,
    type: 'multiple',
    question: '关于 malloc 和 free，下列说法正确的是？',
    options: [
      { id: 'A', text: 'malloc 的参数是需要的字节数' },
      { id: 'B', text: 'malloc 可能返回 NULL，使用前应检查' },
      { id: 'C', text: 'free 之后指针自动变成 NULL' },
      { id: 'D', text: 'malloc 的内存必须手动 free，否则泄漏' },
    ],
    answer: { type: 'multiple', value: ['A', 'B', 'D'] },
    explanation: 'free 不会改写指针变量，它还留着旧地址（悬垂指针），要自己置 NULL。',
    tags: ['malloc', 'free', '内存'],
    errorCategory: 'memory',
  },
  {
    id: 'ch00-q04',
    chapter: 0,
    knowledgePoint: 'sizeof',
    difficulty: 2,
    type: 'exec-result',
    question: '```c\nchar s[] = "hello";\nprintf("%zu %zu", sizeof(s), strlen(s));\n```\n输出什么？',
    options: [
      { id: 'A', text: '5 5' },
      { id: 'B', text: '6 5' },
      { id: 'C', text: '5 6' },
      { id: 'D', text: '6 6' },
    ],
    answer: { type: 'single', value: 'B' },
    explanation: 'sizeof 算整个数组内存（含结尾 \\0，共 6 字节）；strlen 数字符数（不含 \\0，为 5）。',
    tags: ['sizeof', 'strlen', '字符串'],
    errorCategory: 'concept',
  },
  {
    id: 'ch00-q05',
    chapter: 0,
    knowledgePoint: '函数参数',
    difficulty: 2,
    type: 'code-read',
    question: '```c\nvoid change(int x) { x = 100; }\nint main(void) {\n    int a = 1;\n    change(a);\n    printf("%d", a);\n    return 0;\n}\n```\n输出什么？',
    options: [
      { id: 'A', text: '1' },
      { id: 'B', text: '100' },
    ],
    answer: { type: 'single', value: 'A' },
    explanation: 'C 函数参数按值传递，x 是 a 的副本，改 x 不影响 a。想改外部变量必须传地址。',
    tags: ['函数参数', '值传递'],
    errorCategory: 'concept',
  },
  {
    id: 'ch00-q06',
    chapter: 0,
    knowledgePoint: '递归',
    difficulty: 2,
    type: 'exec-result',
    question: '```c\nint f(int n) {\n    if (n <= 1) return 1;\n    return n * f(n - 1);\n}\n```\nf(4) 的返回值是？',
    answer: { type: 'text', value: ['24'] },
    explanation: 'f(4)=4×f(3)=4×3×f(2)=4×3×2×f(1)=4×3×2×1=24。',
    tags: ['递归'],
    errorCategory: 'algorithm',
  },
  {
    id: 'ch00-q07',
    chapter: 0,
    knowledgePoint: 'NULL 与野指针',
    difficulty: 2,
    type: 'bug-find',
    question: '下面的代码有什么问题？\n```c\nint *p;\n*p = 10;\n```',
    options: [
      { id: 'A', text: 'p 未初始化就解引用，p 里是随机地址' },
      { id: 'B', text: '10 应该写成 10.0' },
      { id: 'C', text: '*p 应该写成 p' },
      { id: 'D', text: '没有问题' },
    ],
    answer: { type: 'single', value: 'A' },
    explanation: '野指针：p 未初始化，指向不确定的内存，写入会崩溃或破坏数据。应先 p = &x 或 p = NULL 并判断。',
    tags: ['野指针', 'NULL'],
    errorCategory: 'pointer',
  },

  /* ============ 第 1 章 复杂度 ============ */
  {
    id: 'ch01-q01',
    chapter: 1,
    knowledgePoint: '复杂度判断',
    difficulty: 1,
    type: 'single',
    question: '一个算法的执行时间是 3n² + 5n + 7，它的时间复杂度是？',
    options: [
      { id: 'A', text: 'O(3n²)' },
      { id: 'B', text: 'O(n²)' },
      { id: 'C', text: 'O(n³)' },
      { id: 'D', text: 'O(n)' },
    ],
    answer: { type: 'single', value: 'B' },
    explanation: '大 O 只保留最高阶项并去掉常数：3n²+5n+7 → O(n²)。',
    tags: ['复杂度', '大O'],
    errorCategory: 'complexity',
  },
  {
    id: 'ch01-q02',
    chapter: 1,
    knowledgePoint: '复杂度判断',
    difficulty: 2,
    type: 'single',
    question: '下列复杂度从小到大排序正确的是？',
    options: [
      { id: 'A', text: 'O(1) < O(log n) < O(n) < O(n log n) < O(n²)' },
      { id: 'B', text: 'O(log n) < O(1) < O(n) < O(n²) < O(n log n)' },
      { id: 'C', text: 'O(1) < O(n) < O(log n) < O(n²) < O(n log n)' },
    ],
    answer: { type: 'single', value: 'A' },
    explanation: '标准顺序：O(1) < O(log n) < O(n) < O(n log n) < O(n²) < O(2ⁿ)。',
    tags: ['复杂度'],
    errorCategory: 'complexity',
  },
  {
    id: 'ch01-q03',
    chapter: 1,
    knowledgePoint: '循环复杂度',
    difficulty: 2,
    type: 'single',
    question: '```c\nfor (int i = 0; i < n; i *= 2) …  /* 循环体 O(1) */\n```（i 初值 1）\n这段循环的复杂度是？',
    options: [
      { id: 'A', text: 'O(n)' },
      { id: 'B', text: 'O(log n)' },
      { id: 'C', text: 'O(n log n)' },
      { id: 'D', text: 'O(n²)' },
    ],
    answer: { type: 'single', value: 'B' },
    explanation: 'i 每次翻倍，从 1 到 n 需要乘 log₂n 次。这是二分/倍增类循环的标志。',
    tags: ['复杂度', '循环'],
    errorCategory: 'complexity',
  },
  {
    id: 'ch01-q04',
    chapter: 1,
    knowledgePoint: '查找复杂度',
    difficulty: 2,
    type: 'judge',
    question: '二分查找要求数据有序，且只能在支持随机访问的结构（如数组）上高效进行。',
    options: [
      { id: 'A', text: '正确' },
      { id: 'B', text: '错误' },
    ],
    answer: { type: 'judge', value: true },
    explanation: '链表也可以"二分"，但定位中点要 O(n)，总复杂度退化到 O(n)，得不偿失。',
    tags: ['二分查找', '复杂度'],
    errorCategory: 'concept',
  },
  {
    id: 'ch01-q05',
    chapter: 1,
    knowledgePoint: '空间复杂度',
    difficulty: 2,
    type: 'multiple',
    question: '关于空间复杂度，正确的有？',
    options: [
      { id: 'A', text: '冒泡排序是原地排序，额外空间 O(1)' },
      { id: 'B', text: '归并排序需要 O(n) 的辅助数组' },
      { id: 'C', text: '递归深度也占用栈空间' },
      { id: 'D', text: '快排的空间复杂度一定是 O(1)' },
    ],
    answer: { type: 'multiple', value: ['A', 'B', 'C'] },
    explanation: '快排平均递归深度 O(log n)，栈空间是 O(log n)，不是 O(1)。',
    tags: ['空间复杂度'],
    errorCategory: 'complexity',
  },
  {
    id: 'ch01-q06',
    chapter: 1,
    knowledgePoint: '复杂度估算',
    difficulty: 3,
    type: 'fill',
    question: 'n = 1,000,000 时，O(n log n) 的算法大约执行多少次操作？（数量级，填 10 的幂次方数字，如 20000000）',
    answer: { type: 'text', value: ['20000000', '2×10^7', '2*10^7'] },
    explanation: 'n log₂n ≈ 10⁶ × 20 = 2×10⁷。而 O(n²) 是 10¹²，相差五万倍。',
    tags: ['复杂度', '估算'],
    errorCategory: 'complexity',
  },

  /* ============ 第 2 章 顺序表 ============ */
  {
    id: 'ch02-q01',
    chapter: 2,
    knowledgePoint: '顺序表插入',
    difficulty: 1,
    type: 'single',
    question: '顺序表 [10,20,30]（size=3）在下标 1 插入 15，需要移动几个元素？',
    options: [
      { id: 'A', text: '0 个' },
      { id: 'B', text: '1 个' },
      { id: 'C', text: '2 个' },
      { id: 'D', text: '3 个' },
    ],
    answer: { type: 'single', value: 'C' },
    explanation: '20 和 30 都要后移一格（从后往前挪）。插入下标 i 平均移动 (n+1)/2 个元素。',
    tags: ['顺序表', '插入'],
    errorCategory: 'boundary',
  },
  {
    id: 'ch02-q02',
    chapter: 2,
    knowledgePoint: '插入合法范围',
    difficulty: 2,
    type: 'judge',
    question: '对 size=3 的顺序表，insert(3, x)（在末尾插入）是合法的。',
    options: [
      { id: 'A', text: '正确' },
      { id: 'B', text: '错误' },
    ],
    answer: { type: 'judge', value: true },
    explanation: '插入的合法范围是 0 ≤ pos ≤ size，pos == size 即尾插。写成 pos < size 会丢掉尾插。',
    tags: ['顺序表', '边界'],
    errorCategory: 'boundary',
  },
  {
    id: 'ch02-q03',
    chapter: 2,
    knowledgePoint: '搬移方向',
    difficulty: 2,
    type: 'single',
    question: '顺序表插入时元素应该按什么顺序搬移？',
    options: [
      { id: 'A', text: '从 pos 往后，从前向后挪' },
      { id: 'B', text: '从末尾往 pos，从后向前挪' },
      { id: 'C', text: '随便什么顺序' },
    ],
    answer: { type: 'single', value: 'B' },
    explanation: '从后往前挪，每次写的位置已经"腾空"。从前向后会覆盖还没搬走的数据。',
    tags: ['顺序表', '插入'],
    errorCategory: 'loop',
  },
  {
    id: 'ch02-q04',
    chapter: 2,
    knowledgePoint: '扩容',
    difficulty: 2,
    type: 'multiple',
    question: '顺序表扩容（容量翻倍）时必须做的事？',
    options: [
      { id: 'A', text: 'malloc 新的更大数组' },
      { id: 'B', text: '把旧数据复制过去' },
      { id: 'C', text: 'free 旧数组' },
      { id: 'D', text: '更新 capacity' },
    ],
    answer: { type: 'multiple', value: ['A', 'B', 'C', 'D'] },
    explanation: '四步缺一不可：申请、搬移、释放、记账。忘记 free 就泄漏；忘记 capacity 后续判断就错。',
    tags: ['顺序表', '扩容', 'malloc'],
    errorCategory: 'memory',
  },
  {
    id: 'ch02-q05',
    chapter: 2,
    knowledgePoint: '复杂度',
    difficulty: 2,
    type: 'single',
    question: '顺序表按值查找的平均时间复杂度是？',
    options: [
      { id: 'A', text: 'O(1)' },
      { id: 'B', text: 'O(log n)' },
      { id: 'C', text: 'O(n)' },
      { id: 'D', text: 'O(n²)' },
    ],
    answer: { type: 'single', value: 'C' },
    explanation: '无序数据只能逐个比较。若已排序可用二分 O(log n)。',
    tags: ['顺序表', '查找', '复杂度'],
    errorCategory: 'complexity',
  },
  {
    id: 'ch02-q06',
    chapter: 2,
    knowledgePoint: '顺序表概念',
    difficulty: 1,
    type: 'single',
    question: '顺序表最大的优点是？',
    options: [
      { id: 'A', text: '插入删除快' },
      { id: 'B', text: '按下标随机访问 O(1)' },
      { id: 'C', text: '不浪费任何内存' },
      { id: 'D', text: '不需要连续内存' },
    ],
    answer: { type: 'single', value: 'B' },
    explanation: '连续存储换来随机访问 O(1)。插入删除要搬数据是它的代价。',
    tags: ['顺序表'],
    errorCategory: 'concept',
  },

  /* ============ 第 3 章 单链表 ============ */
  {
    id: 'ch03-q01',
    chapter: 3,
    knowledgePoint: '链表插入顺序',
    difficulty: 1,
    type: 'single',
    question: '在 p 节点后插入 newNode，正确的顺序是？',
    options: [
      { id: 'A', text: 'p->next = newNode; newNode->next = p->next;' },
      { id: 'B', text: 'newNode->next = p->next; p->next = newNode;' },
      { id: 'C', text: '顺序无所谓' },
    ],
    answer: { type: 'single', value: 'B' },
    explanation: '先执行 A 的话，p->next 已指向 newNode，newNode->next = p->next 变成指向自己，后面的链全部丢失（断链）。',
    tags: ['链表', '插入', '断链'],
    errorCategory: 'pointer',
  },
  {
    id: 'ch03-q02',
    chapter: 3,
    knowledgePoint: '链表删除',
    difficulty: 2,
    type: 'multiple',
    question: '删除单链表中 target 节点的正确做法？',
    options: [
      { id: 'A', text: '找到 target 的前驱 prev' },
      { id: 'B', text: 'prev->next = target->next 让链绕过 target' },
      { id: 'C', text: 'free(target) 释放节点' },
      { id: 'D', text: '直接 free(target) 即可，无需前驱' },
    ],
    answer: { type: 'multiple', value: ['A', 'B', 'C'] },
    explanation: '直接 free 会让前驱的 next 变成悬垂指针，后面的节点全部不可达（丢链）。',
    tags: ['链表', '删除'],
    errorCategory: 'pointer',
  },
  {
    id: 'ch03-q03',
    chapter: 3,
    knowledgePoint: '遍历条件',
    difficulty: 2,
    type: 'bug-find',
    question: '遍历带头节点链表输出所有数据节点，哪种循环条件是正确的？（current 初始为 head->next）',
    options: [
      { id: 'A', text: 'while (current->next != NULL)' },
      { id: 'B', text: 'while (current != NULL)' },
      { id: 'C', text: 'while (current != head)' },
    ],
    answer: { type: 'single', value: 'B' },
    explanation: 'A 会漏掉最后一个节点（尾节点 next 是 NULL，直接不进循环体）。空链表时 A 还会对 NULL 解引用崩溃。',
    tags: ['链表', '遍历', '边界'],
    errorCategory: 'boundary',
  },
  {
    id: 'ch03-q04',
    chapter: 3,
    knowledgePoint: '链表 vs 顺序表',
    difficulty: 2,
    type: 'single',
    question: '单链表相比顺序表，说法正确的是？',
    options: [
      { id: 'A', text: '链表支持 O(1) 随机访问' },
      { id: 'B', text: '链表已知节点位置的插入删除只需改指针，O(1)' },
      { id: 'C', text: '链表更省内存' },
      { id: 'D', text: '链表缓存更友好' },
    ],
    answer: { type: 'single', value: 'B' },
    explanation: '链表没有随机访问；每节点多一个指针反而更费内存；节点分散导致缓存不友好。它的优势正是插删不需搬移。',
    tags: ['链表', '对比'],
    errorCategory: 'concept',
  },
  {
    id: 'ch03-q05',
    chapter: 3,
    knowledgePoint: '销毁链表',
    difficulty: 2,
    type: 'code-complete',
    question: '补全销毁链表的代码（两空）：\n```c\nwhile (current != NULL) {\n    Node *next = current->next;  // 为什么要先存？\n    free(current);\n    ____1____;\n}\n____2____ = NULL;\n```',
    answer: { type: 'blanks', value: [['current = next'], ['head']] },
    explanation: 'free 之后再读 current->next 是访问已释放内存（未定义行为），必须先存到局部变量 next。最后 head 置 NULL 防悬垂。',
    tags: ['链表', 'free', '销毁'],
    errorCategory: 'memory',
  },
  {
    id: 'ch03-q06',
    chapter: 3,
    knowledgePoint: '链表执行结果',
    difficulty: 3,
    type: 'exec-result',
    question: '链表 10→20→30，执行：p 指向 10 的节点；p->next->data = 99; 之后链表输出（->分隔）？',
    answer: { type: 'text', value: ['10->99->30', '10 -> 99 -> 30'] },
    explanation: 'p->next 是值为 20 的节点，改它的 data 为 99。',
    tags: ['链表', '执行结果'],
    errorCategory: 'pointer',
  },

  /* ============ 第 4 章 双向链表 ============ */
  {
    id: 'ch04-q01',
    chapter: 4,
    knowledgePoint: '双向链表插入',
    difficulty: 2,
    type: 'single',
    question: '在 p 之后插入 newNode（p 有后继），至少要修改几个指针？',
    options: [
      { id: 'A', text: '2 个' },
      { id: 'B', text: '3 个' },
      { id: 'C', text: '4 个' },
      { id: 'D', text: '1 个' },
    ],
    answer: { type: 'single', value: 'C' },
    explanation: 'newNode->prev、newNode->next、p->next->prev、p->next 共 4 处。',
    tags: ['双向链表', '插入'],
    errorCategory: 'pointer',
  },
  {
    id: 'ch04-q02',
    chapter: 4,
    knowledgePoint: '双向链表删除',
    difficulty: 2,
    type: 'code-complete',
    question: '删除 target（前后都存在）时，两步绕过：\n```c\ntarget->prev->next = ____1____;\ntarget->next->prev = ____2____;\nfree(target);\n```',
    answer: { type: 'blanks', value: [['target->next'], ['target->prev']] },
    explanation: '前驱的 next 跨过 target 指向后继；后继的 prev 指向前驱。两边都要改。',
    tags: ['双向链表', '删除'],
    errorCategory: 'pointer',
  },
  {
    id: 'ch04-q03',
    chapter: 4,
    knowledgePoint: '双向链表优点',
    difficulty: 1,
    type: 'single',
    question: '双向链表相对单链表的核心优势是？',
    options: [
      { id: 'A', text: '更省内存' },
      { id: 'B', text: '找前驱 O(1)' },
      { id: 'C', text: '遍历更快' },
      { id: 'D', text: '实现更简单' },
    ],
    answer: { type: 'single', value: 'B' },
    explanation: '每个节点多存一个 prev 指针（费内存），换来双向可达。',
    tags: ['双向链表'],
    errorCategory: 'concept',
  },
  {
    id: 'ch04-q04',
    chapter: 4,
    knowledgePoint: '空链表插入',
    difficulty: 2,
    type: 'judge',
    question: '双向链表头插时，若链表为空（head->next == NULL），"head->next->prev = newNode"这步应该跳过。',
    options: [
      { id: 'A', text: '正确' },
      { id: 'B', text: '错误' },
    ],
    answer: { type: 'judge', value: true },
    explanation: '此时 head->next 是 NULL，解引用 NULL->prev 会崩溃。这就是头插代码里的 if 判断。',
    tags: ['双向链表', '边界'],
    errorCategory: 'boundary',
  },
  {
    id: 'ch04-q05',
    chapter: 4,
    knowledgePoint: '双向遍历',
    difficulty: 2,
    type: 'exec-result',
    question: '双向链表 1⇄2⇄3，从尾节点出发沿 prev 走到底，输出顺序（-分隔）？',
    answer: { type: 'text', value: ['3-2-1', '3 - 2 - 1'] },
    explanation: '反向遍历：3 → 2 → 1。',
    tags: ['双向链表', '遍历'],
    errorCategory: 'concept',
  },
  {
    id: 'ch04-q06',
    chapter: 4,
    knowledgePoint: '双向链表概念',
    difficulty: 1,
    type: 'multiple',
    question: '关于双向链表，正确的说法有？',
    options: [
      { id: 'A', text: '每个节点含 prev 和 next 两个指针' },
      { id: 'B', text: '删除已知节点不需要先找前驱' },
      { id: 'C', text: '内存开销比单链表大' },
      { id: 'D', text: '头节点的 prev 和尾节点的 next 通常为 NULL' },
    ],
    answer: { type: 'multiple', value: ['A', 'B', 'C', 'D'] },
    explanation: '全对。这正是浏览器前进/后退、LRU 缓存用双向链表的原因。',
    tags: ['双向链表'],
    errorCategory: 'concept',
  },

  /* ============ 第 5 章 栈 ============ */
  {
    id: 'ch05-q01',
    chapter: 5,
    knowledgePoint: '栈的性质',
    difficulty: 1,
    type: 'single',
    question: '入栈顺序 1,2,3,4，可能的出栈序列是？',
    options: [
      { id: 'A', text: '1,2,3,4' },
      { id: 'B', text: '4,3,2,1' },
      { id: 'C', text: '4,1,2,3' },
      { id: 'D', text: 'A 和 B 都可能' },
    ],
    answer: { type: 'single', value: 'D' },
    explanation: '边进边出得 1,2,3,4；全部进完再出得 4,3,2,1。C 不可能：4 出栈后 1 上面的 2、3 必须先出。',
    tags: ['栈', '出栈序列'],
    errorCategory: 'concept',
  },
  {
    id: 'ch05-q02',
    chapter: 5,
    knowledgePoint: '栈操作',
    difficulty: 1,
    type: 'exec-result',
    question: '栈空，依次 push(1) push(2) pop() push(3) peek()，最后 peek 的值和栈内容（底→顶）？',
    answer: { type: 'text', value: ['3，栈内容 1,3', '3 栈内容 1,3', 'peek=3，栈为1,3'] },
    explanation: 'pop 弹出 2；push(3) 后栈为 1,3，栈顶 3。',
    tags: ['栈', 'push', 'pop'],
    errorCategory: 'algorithm',
  },
  {
    id: 'ch05-q03',
    chapter: 5,
    knowledgePoint: '括号匹配',
    difficulty: 2,
    type: 'single',
    question: '括号匹配算法中，遇到右括号时应该？',
    options: [
      { id: 'A', text: '入栈' },
      { id: 'B', text: '弹栈顶并检查是否配对' },
      { id: 'C', text: '直接返回匹配成功' },
    ],
    answer: { type: 'single', value: 'B' },
    explanation: '左括号入栈等待；右括号弹栈配对。栈空时遇到右括号 = 右括号多了。',
    tags: ['栈', '括号匹配'],
    errorCategory: 'algorithm',
  },
  {
    id: 'ch05-q04',
    chapter: 5,
    knowledgePoint: '括号匹配',
    difficulty: 2,
    type: 'judge',
    question: '字符串 "([)]" 的括号是匹配的。',
    options: [
      { id: 'A', text: '正确' },
      { id: 'B', text: '错误' },
    ],
    answer: { type: 'judge', value: false },
    explanation: '数量相等但类型交叉不匹配。遇到 ) 时栈顶是 [，类型不符。',
    tags: ['括号匹配'],
    errorCategory: 'algorithm',
  },
  {
    id: 'ch05-q05',
    chapter: 5,
    knowledgePoint: '栈复杂度',
    difficulty: 1,
    type: 'single',
    question: '栈的 push/pop/判空操作的时间复杂度分别是？',
    options: [
      { id: 'A', text: 'O(1) O(1) O(1)' },
      { id: 'B', text: 'O(n) O(n) O(1)' },
      { id: 'C', text: 'O(log n) O(log n) O(1)' },
    ],
    answer: { type: 'single', value: 'A' },
    explanation: '栈只在栈顶操作，限制操作换来全 O(1)。',
    tags: ['栈', '复杂度'],
    errorCategory: 'complexity',
  },
  {
    id: 'ch05-q06',
    chapter: 5,
    knowledgePoint: '栈下溢',
    difficulty: 2,
    type: 'bug-find',
    question: '顺序栈 pop 操作最容易犯的错误是？',
    options: [
      { id: 'A', text: '忘记先判空，空栈弹出读到垃圾数据' },
      { id: 'B', text: '忘记返回值' },
      { id: 'C', text: '忘记 malloc' },
    ],
    answer: { type: 'single', value: 'A' },
    explanation: 'top==0 时继续 pop 会下溢：读无效内存甚至 top 变 -1 导致越界。',
    tags: ['栈', '下溢'],
    errorCategory: 'boundary',
  },

  /* ============ 第 6 章 队列 ============ */
  {
    id: 'ch06-q01',
    chapter: 6,
    knowledgePoint: '循环队列判满',
    difficulty: 2,
    type: 'single',
    question: '容量为 6 的循环队列（留一空位法），最多能存多少个元素？判满条件是？',
    options: [
      { id: 'A', text: '6 个；(rear+1)%6 == front' },
      { id: 'B', text: '5 个；(rear+1)%6 == front' },
      { id: 'C', text: '5 个；rear == front' },
      { id: 'D', text: '6 个；rear == front - 1' },
    ],
    answer: { type: 'single', value: 'B' },
    explanation: '牺牲一个格子区分空（front==rear）与满。容量 n 实际容量 n-1。',
    tags: ['循环队列', '判满'],
    errorCategory: 'boundary',
  },
  {
    id: 'ch06-q02',
    chapter: 6,
    knowledgePoint: '取模回绕',
    difficulty: 2,
    type: 'exec-result',
    question: '容量 6 的循环队列，front=4, rear=5。enqueue 后 rear 变成多少？再 dequeue 后 front 变成多少？',
    answer: { type: 'text', value: ['rear=0，front=5', 'rear=0 front=5', '0 和 5', 'rear:0 front:5'] },
    explanation: '(5+1)%6=0 回绕；(4+1)%6=5。',
    tags: ['循环队列', '取模'],
    errorCategory: 'algorithm',
  },
  {
    id: 'ch06-q03',
    chapter: 6,
    knowledgePoint: '假溢出',
    difficulty: 2,
    type: 'single',
    question: '朴素顺序队列"假溢出"指的是？',
    options: [
      { id: 'A', text: '数组物理满了' },
      { id: 'B', text: 'rear 到达数组末尾报满，但 front 前面有空位用不上' },
      { id: 'C', text: '内存泄漏' },
    ],
    answer: { type: 'single', value: 'B' },
    explanation: '空间没用完却不能继续入队。循环队列用取模解决。',
    tags: ['队列', '假溢出'],
    errorCategory: 'concept',
  },
  {
    id: 'ch06-q04',
    chapter: 6,
    knowledgePoint: '链队列空队',
    difficulty: 3,
    type: 'bug-find',
    question: '链队列出队到只剩 1 个节点时，容易漏掉什么？',
    options: [
      { id: 'A', text: '忘记把 rear 也置 NULL，下次入队解引用悬垂指针' },
      { id: 'B', text: '忘记 print' },
      { id: 'C', text: '忘记比较大小' },
    ],
    answer: { type: 'single', value: 'A' },
    explanation: '最后一个节点出队后 front=NULL，rear 若仍指旧节点，enqueue 时 rear->next 就是访问已释放内存。',
    tags: ['链队列', '边界'],
    errorCategory: 'pointer',
  },
  {
    id: 'ch06-q05',
    chapter: 6,
    knowledgePoint: '队列性质',
    difficulty: 1,
    type: 'judge',
    question: '队列是先进先出（FIFO）：从队尾入队，从队头出队。',
    options: [
      { id: 'A', text: '正确' },
      { id: 'B', text: '错误' },
    ],
    answer: { type: 'judge', value: true },
    explanation: '与栈（LIFO）相对。BFS 依赖队列保证"先发现的先处理"。',
    tags: ['队列'],
    errorCategory: 'concept',
  },
  {
    id: 'ch06-q06',
    chapter: 6,
    knowledgePoint: '循环队列计算',
    difficulty: 3,
    type: 'fill',
    question: '容量 8 的循环队列，front=3, rear=3。此时队列中有多少个元素？',
    answer: { type: 'text', value: ['0'] },
    explanation: 'front == rear 表示空队列，0 个元素。（若采用 count 计数法需另给 count 才能判断。）',
    tags: ['循环队列'],
    errorCategory: 'boundary',
  },
];
